version: "3.9"

services:
  cosmos-odyssey-app:
    container_name: "cosmos-odyssey-app"
    build:
      dockerfile: ./Dockerfile
    ports:
      # external:internal
      - "8000:8080"
    environment:
      - ConnectionStrings:DefaultConnection=Host=cosmos-odyssey-db:5432;Database=cosmos-odyssey-db;Username=postgres;Password=postgres
    depends_on:
      - cosmos-odyssey-db

  cosmos-odyssey-db:
    container_name: "cosmos-odyssey-db"
    image: "postgres:15.2-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      # external:internal
      - "5445:5432"
    volumes:
      - "cosmos-odyssey-db-postgres-volume:/var/lib/postgresql/data"

volumes:
  cosmos-odyssey-db-postgres-volume: